version: "3.5"

services:
  api01: &api
    image: rinha
    hostname: api01
    environment:
      - DB_INITIAL_POOL_SIZE=13
      - DB_MAX_POOL_SIZE=13
      - API_USE_DB_FUNC=true
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "120MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

  postgres:
    container_name: rinha-rust-postgres
    image: postgres:15
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "290MB"


networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1